USE [master]
GO

/****** Object:  Database [UserList]    Script Date: 30.07.2019 16:23:51 ******/
CREATE DATABASE [UserList]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'User', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\User.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'User_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\User_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [UserList] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserList].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserList] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserList] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserList] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserList] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserList] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserList] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserList] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserList] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserList] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserList] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserList] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserList] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserList] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserList] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserList] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserList] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserList] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserList] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserList] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserList] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserList] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserList] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserList] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserList] SET  MULTI_USER 
GO

ALTER DATABASE [UserList] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserList] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserList] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserList] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UserList] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserList] SET QUERY_STORE = OFF
GO

USE [UserList]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [UserList] SET  READ_WRITE 
GO


